### ISSUE TITLE
Path must be a string or Buffer

### ISSUE THREAD

**Issue by ajsb85** [ritz078/starring#5]
```CMD
C:\>starring --all
fs.js:274
  binding.open(pathModule._makeLong(path),
          ^

TypeError: path must be a string or Buffer
    at Object.fs.readFile (fs.js:274:11)
    at C:\Users\user\AppData\Roaming\npm\node_modules\starring\node_modules\load-pkg\index.js:26:8
    at C:\Users\user\AppData\Roaming\npm\node_modules\starring\node_modules\find-file-up\index.js:50:9
    at C:\Users\user\AppData\Roaming\npm\node_modules\starring\node_modules\find-file-up\index.js:93:7
    at FSReqWrap.oncomplete (fs.js:112:15)
```

**Comment by ritz078** [comment]
This error is because you not inside any project folder. Definitely a better error message would help.

**Comment by ritz078** [comment]
Let me know if fixed in the latest version.

**Comment by ajsb85** [comment]
> ✖ No package.json found. Ensure that you are inside the project directory.

Fixed 👍
